packages:
  - 'packages/**'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.1
  vitest: 5.0.0
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - react
    - react-dom
    - '@types/react'
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
