name: Build and Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v0.6.0
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build-and-publish-to-npm:
    runs-on: ubuntu-latest
    name: Build and Publish to NPM
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build distribution
        run: pnpm build

      - name: Publish to NPM
        if: "startsWith(github.ref, 'refs/tags/')"
        run: pnpm -r publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

  publish-to-github-release:
    runs-on: ubuntu-latest
    name: Publish to GitHub Release
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ env.RELEASE_VERSION }}
