name: Test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true

      - name: Install dependencies
        run: vp i --frozen-lockfile

      - name: Build VitePress site
        run: vp docs:build

      - name: Test using vitest
        run: pnpm test
